Update validate_secrets.yml

diff --git a/.github/workflows/validate_secrets.yml b/.github/workflows/validate_secrets.yml
--- a/.github/workflows/validate_secrets.yml
+++ b/.github/workflows/validate_secrets.yml
@@ -1,189 +1,174 @@
-name: 1. Validate Secrets
-run-name: Validate Secrets (${{ github.ref_name }})
-on: [workflow_call, workflow_dispatch]
+名字：1.验证秘密
+运行名称：验证秘密（${{ github.ref_name }}）
+打开：[工作流程_调用，工作流程_分流]
 
-jobs:
-  validate-access-token:
-    name: Access
-    runs-on: ubuntu-latest
-    env:
-      GH_PAT: ${{ secrets.GH_PAT }}
-      GH_TOKEN: ${{ secrets.GH_PAT }}
-    outputs:
-      HAS_WORKFLOW_PERMISSION: ${{ steps.access-token.outputs.has_workflow_permission }}
-    steps:
-      - name: Validate Access Token
-        id: access-token
-        run: |
-          # Validate Access Token
-
-          # Ensure that gh exit codes are handled when output is piped.
-          set -o pipefail
-
-          # Define patterns to validate the access token (GH_PAT) and distinguish between classic and fine-grained tokens.
-          GH_PAT_CLASSIC_PATTERN='^ghp_[a-zA-Z0-9]{36}$'
-          GH_PAT_FINE_GRAINED_PATTERN='^github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59}$'
-
-          # Validate Access Token (GH_PAT)
-          if [ -z "$GH_PAT" ]; then
-            failed=true
-            echo "::error::The GH_PAT secret is unset or empty. Set it and try again."
-          else
-            if [[ $GH_PAT =~ $GH_PAT_CLASSIC_PATTERN ]]; then
-              provides_scopes=true
-              echo "The GH_PAT secret is a structurally valid classic token."
-            elif [[ $GH_PAT =~ $GH_PAT_FINE_GRAINED_PATTERN ]]; then
-              echo "The GH_PAT secret is a structurally valid fine-grained token."
-            else
-              unknown_format=true
-              echo "The GH_PAT secret does not have a known token format."
-            fi
+工作：
+  验证访问令牌：
+    名称：访问
+    运行：ubuntu-latest
+    环境：
+      GH_PAT：${{ secrets.GH_PAT }}
+      GH_TOKEN：${{ secrets.GH_PAT }}
+    输出：
+      HAS_WORKFLOW_PERMISSION：${{ steps.access-token.outputs.has_workflow_permission }}
+    步骤：
+-名称：验证访问令牌
+        id：访问令牌
+        运行：|
+# 验证访问令牌
+# 确保在输出管道时处理 gh 出口代码。
+设置-o管道故障
+# 定义模式来验证访问令牌（GH_PAT），并区分经典令牌和精细令牌。
+GH_PAT_CLASSIC_PATTERN='^ghp_[a-zA-Z0-9]{36}$'
+GH_PAT_FINE_GRAINED_PATTERN='^github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59}$'
+# 验证访问令牌 (GH_PAT)
+如果[-z "$GH_PAT"]；那么
+失败=真
+回声“::错误::GH_PAT密钥未设置或为空。设置它，然后重试。”
+其他
+如果[[ $GH_PAT =~ $GH_PAT_CLASSIC_PATTERN ]]；那么
+提供_范围=真
+回声“GH_PAT秘密是一个结构上有效的经典令牌。”
+elif [[ $GH_PAT =~ $GH_PAT_FINE_GRAINED_PATTERN ]];然后
+回声“GH_PAT秘密是一个结构上有效的精细令牌。”
+其他
+未知_格式=真
+回声“GH_PAT秘密没有已知的令牌格式。”
+菲
             
-            # Attempt to capture the x-oauth-scopes scopes of the token.
-            if ! scopes=$(curl -sS -f -I -H "Authorization: token $GH_PAT" https://api.github.com | { grep -i '^x-oauth-scopes:' || true; } | cut -d ' ' -f2- | tr -d '\r'); then
-              failed=true
-              if [ $unknown_format ]; then
-                echo "::error::Unable to connect to GitHub using the GH_PAT secret. Verify that it is set correctly (including the 'ghp_' or 'github_pat_' prefix) and try again."
-              else
-                echo "::error::Unable to connect to GitHub using the GH_PAT secret. Verify that the token exists and has not expired at https://github.com/settings/tokens. If necessary, regenerate or create a new token (and update the secret), then try again."
-              fi
-            elif [[ $scopes =~ workflow ]]; then
-              echo "The GH_PAT secret has repo and workflow permissions."
-              echo "has_workflow_permission=true" >> $GITHUB_OUTPUT
-            elif [[ $scopes =~ repo ]]; then
-              echo "The GH_PAT secret has repo (but not workflow) permissions."
-            elif [ $provides_scopes ]; then
-              failed=true
-              if [ -z "$scopes" ]; then
-                echo "The GH_PAT secret is valid and can be used to connect to GitHub, but it does not provide any permission scopes."
-              else
-                echo "The GH_PAT secret is valid and can be used to connect to GitHub, but it only provides the following permission scopes: $scopes"
-              fi
-              echo "::error::The GH_PAT secret is lacking at least the 'repo' permission scope required to access the Match-Secrets repository. Update the token permissions at https://github.com/settings/tokens (to include the 'repo' and 'workflow' scopes) and try again."
-            else
-              echo "The GH_PAT secret is valid and can be used to connect to GitHub, but it does not provide inspectable scopes. Assuming that the 'repo' and 'workflow' permission scopes required to access the Match-Secrets repository and perform automations are present."
-              echo "has_workflow_permission=true" >> $GITHUB_OUTPUT
-            fi
-          fi
-
-          # Exit unsuccessfully if secret validation failed.
-          if [ $failed ]; then
-            exit 2
-          fi
-
-      - name: Validate Match-Secrets
-        run: |
-          # Validate Match-Secrets
-
-          # Ensure that gh exit codes are handled when output is piped.
-          set -o pipefail
-
-          # If a Match-Secrets repository does not exist, attempt to create one.
-          if ! visibility=$(gh repo view ${{ github.repository_owner }}/Match-Secrets --json visibility | jq --raw-output '.visibility | ascii_downcase'); then
-            echo "A '${{ github.repository_owner }}/Match-Secrets' repository could not be found using the GH_PAT secret. Attempting to create one..."
+# 尝试捕获令牌的x-oauth-scopes范围。
+如果！scopes=$(curl -sS -f -I -H "授权：令牌 $GH_PAT" https://api.github.com | { grep -i '^x-oauth-scopes:' || true; } | cut -d ' ' -f2- | tr -d '\r');然后
+失败=真
+如果[$未知_格式]；那么
+echo "::error::无法使用GH_PAT密钥连接到GitHub。验证其设置是否正确（包括'ghp_'或'github_pat_'前缀），然后重试。”
+其他
+echo "::error::无法使用GH_PAT密钥连接到GitHub。在https://github.com/settings/tokens上驗證令牌存在且未過期。如有必要，请重新生成或创建新令牌（并更新秘密），然后重试。”
+菲
+elif [[ $scopes =~ 工作流程 ]];然后
+回声“GH_PAT密钥具有回购和工作流程权限。”
+回声“has_workflow_permission=true” >> $GITHUB_OUTPUT
+elif [[ $scopes =~ repo ]]；然后
+回声“GH_PAT密钥具有回购（但不是工作流程）权限。”
+elif [ $provides_scopes ]; 然后
+失败=真
+如果[-z“$scopes”]；那么
+回声“GH_PAT密钥是有效的，可用于连接到GitHub，但它不提供任何权限范围。”
+其他
+回声“GH_PAT密钥是有效的，可用于连接到GitHub，但它只提供以下权限范围：$scopes”
+菲
+echo "::error::GH_PAT秘密至少缺乏访问Match-Secrets存储库所需的“repo”权限范围。在https://github.com/settings/tokens上更新令牌权限（以包括'repo'和'workflow'范围），然后重试。”
+其他
+回声“GH_PAT密钥是有效的，可用于连接到GitHub，但它不提供可检查的范围。假设访问Match-Secrets存储库和执行自动化所需的'repo'和'workflow'权限范围存在。”
+回声“has_workflow_permission=true” >> $GITHUB_OUTPUT
+菲
+菲
+# 如果秘密验证失败，则退出失败。
+如果[$失败]；那么
+2号出口
+菲
+-名称：验证匹配机密
+        运行：|
+# 验证匹配秘密
+# 确保在输出管道时处理 gh 出口代码。
+设置-o管道故障
+# 如果不存在Match-Secrets存储库，请尝试创建一个。
+如果！visibility=$(gh repo view ${{ github.repository_owner }}/Match-Secrets --json visibility | jq --raw-output '.visibility | ascii_downcase');然后
+回声“使用GH_PAT密钥找不到'${{ github.repository_owner }}/Match-Secrets'存储库。尝试创建一个......”
             
-            # Create a private Match-Secrets repository and verify that it exists and that it is private.
-            if gh repo create ${{ github.repository_owner }}/Match-Secrets --private >/dev/null && [ "$(gh repo view ${{ github.repository_owner }}/Match-Secrets --json visibility | jq --raw-output '.visibility | ascii_downcase')" == "private" ]; then
-              echo "Created a private '${{ github.repository_owner }}/Match-Secrets' repository."
-            else
-              failed=true
-              echo "::error::Unable to create a private '${{ github.repository_owner }}/Match-Secrets' repository. Create a private 'Match-Secrets' repository manually and try again. If a private 'Match-Secrets' repository already exists, verify that the token permissions of the GH_PAT are set correctly (or update them) at https://github.com/settings/tokens and try again."
-            fi
-          # Otherwise, if a Match-Secrets repository exists, but it is public, cause validation to fail.
-          elif [[ "$visibility" == "public" ]]; then
-            failed=true
-            echo "::error::A '${{ github.repository_owner }}/Match-Secrets' repository was found, but it is public. Change the repository visibility to private (or delete it) and try again. If necessary, a private repository will be created for you."
-          else
-            echo "Found a private '${{ github.repository_owner }}/Match-Secrets' repository to use."
-          fi
+# 创建私人Match-Secrets存储库，并验证它是否存在并且是私人的。
+如果gh repo创建${{ github.repository_owner }}/Match-Secrets --private >/dev/null && [ "$(gh repo view ${{ github.repository_owner }}/Match-Secrets --json visibility | jq --raw-output '.visibility | ascii_downcase')) == "private" ];然后
+回声“创建了一个私人'${{ github.repository_owner }}/Match-Secrets'存储库。”
+其他
+失败=真
+echo "::error::无法创建私人'${{ github.repository_owner }}/Match-Secrets'存储库。手动创建一个私人的“Match-Secrets”存储库，然后重试。如果已经存在私人'Match-Secrets'存储库，请在https://github.com/settings/tokens上验证GH_PAT的令牌权限是否正确设置（或更新），然后重试。”
+菲
+# 否则，如果存在Match-Secrets存储库，但它是公开的，则会导致验证失败。
+elif [[ "$visibility" == "public" ]];然后
+失败=真
+echo "::error::A '${{ github.repository_owner }}/Match-Secrets'存储库已找到，但但是公开的。将存储库可见性更改为私密（或将其删除），然后重试。如有必要，将为您创建一个私人存储库。”
+其他
+回声“找到了一个私人的'${{ github.repository_owner }}/Match-Secrets'存储库来使用。”
+菲
+# 如果秘密验证失败，则退出失败。
+如果[$失败]；那么
+2号出口
+菲
+  验证-快速通道-秘密：
+    名称：Fastlane
+    需求：[验证-访问-令牌]
+    运行：macos-15
+    环境：
+      GH_PAT：${{ secrets.GH_PAT }}
+      GH_TOKEN：${{ secrets.GH_PAT }}
+      FASTLANE_ISSUER_ID：${{ secrets.FASTLANE_ISSUER_ID }}
+      FASTLANE_KEY_ID：${{ secrets.FASTLANE_KEY_ID }}
+      FASTLANE_KEY：${{ secrets.FASTLANE_KEY }}
+      匹配_密码：${{ secrets.MATCH_PASSWORD }}
+      团队ID：${{ secrets.TEAMID }}
+    步骤：
+- 名称：结账回购
+        用途：actions/checkout@v4
 
-          # Exit unsuccessfully if secret validation failed.
-          if [ $failed ]; then
-            exit 2
-          fi
+-名称：安装项目依赖项
+        运行：捆绑安装
 
-  validate-fastlane-secrets:
-    name: Fastlane
-    needs: [validate-access-token]
-    runs-on: macos-26
-    env:
-      GH_PAT: ${{ secrets.GH_PAT }}
-      GH_TOKEN: ${{ secrets.GH_PAT }}
-      FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
-      FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
-      FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}
-      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
-      TEAMID: ${{ secrets.TEAMID }}
-    steps:
-      - name: Checkout Repo
-        uses: actions/checkout@v5
+      #将GitHub运行时钟与Windows时间服务器同步（https://github.com/actions/runner/issues/2996中建议的变通方法）
+-名称：同步时钟
+        运行：sudo sntp -sS time.windows.com
 
-      - name: Install Project Dependencies
-        run: bundle install
-
-      # Sync the GitHub runner clock with the Windows time server (workaround as suggested in https://github.com/actions/runner/issues/2996)
-      - name: Sync clock
-        run: sudo sntp -sS time.windows.com
-
-      - name: Validate Fastlane Secrets
-        run: |
-          # Validate Fastlane Secrets
-
-          # Validate TEAMID
-          if [ -z "$TEAMID" ]; then
-            failed=true
-            echo "::error::The TEAMID secret is unset or empty. Set it and try again."
-          elif [ ${#TEAMID} -ne 10 ]; then
-            failed=true
-            echo "::error::The TEAMID secret is set but has wrong length. Verify that it is set correctly and try again."
-          elif ! [[ $TEAMID =~ ^[A-Z0-9]+$ ]]; then
-            failed=true
-            echo "::error::The TEAMID secret is set but invalid. Verify that it is set correctly (only uppercase letters and numbers) and try again."
-          fi
-
-          # Validate MATCH_PASSWORD
-          if [ -z "$MATCH_PASSWORD" ]; then
-            failed=true
-            echo "::error::The MATCH_PASSWORD secret is unset or empty. Set it and try again."
-          fi
-
-          # Ensure that fastlane exit codes are handled when output is piped.
-          set -o pipefail
-
-          # Validate FASTLANE_ISSUER_ID, FASTLANE_KEY_ID, and FASTLANE_KEY
-          FASTLANE_KEY_ID_PATTERN='^[A-Z0-9]+$'
-          FASTLANE_ISSUER_ID_PATTERN='^\{?[A-F0-9a-f]{8}-[A-F0-9a-f]{4}-[A-F0-9a-f]{4}-[A-F0-9a-f]{4}-[A-F0-9a-f]{12}\}?$'
-
-          if [ -z "$FASTLANE_ISSUER_ID" ] || [ -z "$FASTLANE_KEY_ID" ] || [ -z "$FASTLANE_KEY" ]; then
-            failed=true
-            [ -z "$FASTLANE_ISSUER_ID" ] && echo "::error::The FASTLANE_ISSUER_ID secret is unset or empty. Set it and try again."
-            [ -z "$FASTLANE_KEY_ID"    ] && echo "::error::The FASTLANE_KEY_ID secret is unset or empty. Set it and try again."
-            [ -z "$FASTLANE_KEY"       ] && echo "::error::The FASTLANE_KEY secret is unset or empty. Set it and try again."
-          elif [ ${#FASTLANE_KEY_ID} -ne 10 ]; then
-            failed=true
-            echo "::error::The FASTLANE_KEY_ID secret is set but has wrong length. Verify that you copied it correctly from the 'Keys' tab at https://appstoreconnect.apple.com/access/integrations/api and try again."
-          elif ! [[ $FASTLANE_KEY_ID =~ $FASTLANE_KEY_ID_PATTERN ]]; then
-            failed=true
-            echo "::error::The FASTLANE_KEY_ID secret is set but invalid. Verify that you copied it correctly from the 'Keys' tab at https://appstoreconnect.apple.com/access/integrations/api and try again."
-          elif ! [[ $FASTLANE_ISSUER_ID =~ $FASTLANE_ISSUER_ID_PATTERN ]]; then
-            failed=true
-            echo "::error::The FASTLANE_ISSUER_ID secret is set but invalid. Verify that you copied it correctly from the 'Keys' tab at https://appstoreconnect.apple.com/access/integrations/api and try again."
-          elif ! echo "$FASTLANE_KEY" | openssl pkcs8 -nocrypt >/dev/null; then
-            failed=true
-            echo "::error::The FASTLANE_KEY secret is set but invalid. Verify that you copied it correctly from the API Key file (*.p8) you downloaded and try again."
-          elif ! bundle exec fastlane validate_secrets 2>&1 | tee fastlane.log; then
-            if grep -q "Couldn't decrypt the repo" fastlane.log; then
-              failed=true
-              echo "::error::Unable to decrypt the Match-Secrets repository using the MATCH_PASSWORD secret. Verify that it is set correctly and try again."
-            elif grep -q -e "required agreement" -e "license agreement" fastlane.log; then
-              failed=true
-              echo "::error::❗️ Verify that the latest developer program license agreement has been accepted at https://developer.apple.com/account (review and accept any updated agreement), then wait a few minutes for changes to take effect and try again."
-            elif grep -q "Your certificate .* is not valid" fastlane.log; then
-              echo "::notice::Your Distribution certificate is invalid or expired. Automated renewal of the certificate will be attempted."
-            fi
-          fi
-
-          # Exit unsuccessfully if secret validation failed.
-          if [ $failed ]; then
-            exit 2
-          fi
+-名称：验证Fastlane秘密
+        运行：|
+# 验证 Fastlane 秘密
+# 验证团队ID
+如果[-z“$TEAMID”]；那么
+失败=真
+echo "::错误::TEAMID秘密未设置或为空。设置它，然后重试。”
+elif [ ${#TEAMID} -ne 10 ];然后
+失败=真
+echo "::error::TEAMID秘密已设置，但长度错误。验证设置是否正确，然后重试。”
+埃菲夫！[[$TEAMID =~ ^[A-Z0-9]+$ ]];然后
+失败=真
+echo "::error::TEAMID密钥已设置，但无效。验证其设置是否正确（只大写字母和数字），然后重试。”
+菲
+# 验证匹配_密码
+如果[-z“$MATCH_PASSWORD”]；那么
+失败=真
+echo "::错误::The MATCH_PASSWORD 秘密未设置或为空。设置它，然后重试。”
+菲
+# 确保在输出管道时处理快速通道出口代码。
+设置-o管道故障
+# 验证 FASTLANE_ISSUER_ID、FASTLANE_KEY_ID 和 FASTLANE_KEY
+FASTLANE_KEY_ID_PATTERN='^[A-Z0-9]+$'
+FASTLANE_ISSUER_ID_PATTERN='^\{?[A-F0-9a-f]{8}-[A-F0-9a-f]{4}-[A-F0-9a-f]{4}-[A-F0-9a-f]{4}-[A-F0-9a-f]{12}\}？美元'
+如果[ -z "$FASTLANE_ISSUER_ID" ] || [ -z "$FASTLANE_KEY_ID" ] || [ -z "$FASTLANE_KEY"] ] 然後
+失败=真
+[ -z "$FASTLANE_ISSUER_ID" ] && echo "::error::FASTLANE_ISSUER_ID 密钥未设置或为空。设置它，然后重试。”
+[ -z "$FASTLANE_KEY_ID" ] && echo "::错误::FASTLANE_KEY_ID 密钥未设置或为空。设置它，然后重试。”
+[ -z "$FASTLANE_KEY" ] && echo "::error::FASTLANE_KEY 秘密未设置或为空。设置它，然后重试。”
+elif [ ${#FASTLANE_KEY_ID} -ne 10 ]; 然后
+失败=真
+echo "::error::FASTLANE_KEY_ID秘密已设置，但长度错误。验证您是否从https://appstoreconnect.apple.com/access/integrations/api 上的“密钥”标签页中正确拷贝了它，然后重试。”
+埃菲夫！[[$FASTLANE_KEY_ID =~ $FASTLANE_KEY_ID_PATTERN ]]；然后
+失败=真
+echo "::错误::FASTLANE_KEY_ID 密钥已设置，但无效。验证您是否从https://appstoreconnect.apple.com/access/integrations/api 上的“密钥”标签页中正确拷贝了它，然后重试。”
+埃菲夫！[[$FASTLANE_ISSUER_ID =~ $FASTLANE_ISSUER_ID_PATTERN ]]；然后
+失败=真
+echo "::error::FASTLANE_ISSUER_ID 密钥已设置，但无效。验证您是否从https://appstoreconnect.apple.com/access/integrations/api 上的“密钥”标签页中正确拷贝了它，然后重试。”
+埃菲夫！回声“$FASTLANE_KEY” | openssl pkcs8 -nocrypt >/dev/null；然后
+失败=真
+echo "::error::FASTLANE_KEY 秘密已设置，但无效。验证是否从下载的API密钥文件（*.p8）中正确复制了它，然后重试。”
+埃菲夫！捆绑执行fastlane验证_secrets 2>&1 | tee fastlane.log；然后
+如果grep -q“无法解密repo”fastlane.log；那么
+失败=真
+echo "::错误::无法使用MATCH_PASSWORD密钥解密Match-Secrets存储库。验证设置是否正确，然后重试。”
+elif grep -q -e“所需协议”-e“许可协议”fastlane.log；然后
+失败=真
+echo "::error::❗️ 验证最新的开发者计划许可协议是否已通过 https://developer.apple.com/account (查看并接受任何更新的协议)，然后等待几分钟更改生效，然后重试。"
+elif grep -q“您的证书。*无效”fastlane.log；然后
+echo "::notice::您的分发证书无效或已过期。将尝试自动更新证书。”
+菲
+菲
+# 如果秘密验证失败，则退出失败。
+如果[$失败]；那么
+2号出口
+菲
